---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: rancher/dapper:v0.5.7
    commands:
      - dapper ci
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: docker-publish-master
    image: plugins/docker
    settings:
      build_args:
        - ARCH=amd64
        - VERSION=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}-head
      dockerfile: package/Dockerfile
      password:
        from_secret: docker_password
      repo: "rancher/harvester-network-controller"
      tag: ${DRONE_BRANCH}-head-linux-amd64
      username:
        from_secret: docker_username
    when:
      ref:
        include:
          - "refs/heads/master"
          - "refs/heads/release/v*"
      event:
        - push

  - name: docker-publish-master-helper
    image: plugins/docker
    settings:
      build_args:
        - ARCH=amd64
        - VERSION=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}-head
      dockerfile: package/Dockerfile.helper
      password:
        from_secret: docker_password
      repo: "rancher/harvester-network-helper"
      tag: ${DRONE_BRANCH}-head-linux-amd64
      username:
        from_secret: docker_username
    when:
      ref:
        include:
          - "refs/heads/master"
          - "refs/heads/release/v*"
      event:
        - push

  - name: docker-publish-master-webhook
    image: plugins/docker
    settings:
      build_args:
        - ARCH=amd64
        - VERSION=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}-head
      dockerfile: package/Dockerfile.webhook
      password:
        from_secret: docker_password
      repo: "rancher/harvester-network-webhook"
      tag: ${DRONE_BRANCH}-head-linux-amd64
      username:
        from_secret: docker_username
    when:
      ref:
        include:
          - "refs/heads/master"
          - "refs/heads/release/v*"
      event:
        - push

  - name: docker-publish
    image: plugins/docker
    settings:
      dockerfile: package/Dockerfile
      password:
        from_secret: docker_password
      repo: "rancher/harvester-network-controller"
      tag: "${DRONE_TAG}-linux-amd64"
      username:
        from_secret: docker_username
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

  - name: docker-publish-helper
    image: plugins/docker
    settings:
      dockerfile: package/Dockerfile.helper
      password:
        from_secret: docker_password
      repo: "rancher/harvester-network-helper"
      tag: "${DRONE_TAG}-linux-amd64"
      username:
        from_secret: docker_username
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

  - name: docker-publish-webhook
    image: plugins/docker
    settings:
      dockerfile: package/Dockerfile.webhook
      password:
        from_secret: docker_password
      repo: "rancher/harvester-network-webhook"
      tag: "${DRONE_TAG}-linux-amd64"
      username:
        from_secret: docker_username
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: rancher/dapper:v0.5.7
    commands:
      - dapper ci
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: docker-publish-master
    image: plugins/docker
    settings:
      build_args:
        - ARCH=arm64
        - VERSION=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}-head
      dockerfile: package/Dockerfile
      password:
        from_secret: docker_password
      repo: "rancher/harvester-network-controller"
      tag: ${DRONE_BRANCH}-head-linux-arm64
      username:
        from_secret: docker_username
    when:
      ref:
        include:
          - "refs/heads/master"
          - "refs/heads/release/v*"
      event:
        - push

  - name: docker-publish-master-helper
    image: plugins/docker
    settings:
      build_args:
        - ARCH=arm64
        - VERSION=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}-head
      dockerfile: package/Dockerfile.helper
      password:
        from_secret: docker_password
      repo: "rancher/harvester-network-helper"
      tag: ${DRONE_BRANCH}-head-linux-arm64
      username:
        from_secret: docker_username
    when:
      ref:
        include:
          - "refs/heads/master"
          - "refs/heads/release/v*"
      event:
        - push

  - name: docker-publish-master-webhook
    image: plugins/docker
    settings:
      build_args:
        - ARCH=arm64
        - VERSION=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}-head
      dockerfile: package/Dockerfile.webhook
      password:
        from_secret: docker_password
      repo: "rancher/harvester-network-webhook"
      tag: ${DRONE_BRANCH}-head-linux-arm64
      username:
        from_secret: docker_username
    when:
      ref:
        include:
          - "refs/heads/master"
          - "refs/heads/release/v*"
      event:
        - push

  - name: docker-publish
    image: plugins/docker
    settings:
      dockerfile: package/Dockerfile
      password:
        from_secret: docker_password
      repo: "rancher/harvester-network-controller"
      tag: "${DRONE_TAG}-linux-arm64"
      username:
        from_secret: docker_username
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

  - name: docker-publish-helper
    image: plugins/docker
    settings:
      dockerfile: package/Dockerfile.helper
      password:
        from_secret: docker_password
      repo: "rancher/harvester-network-helper"
      tag: "${DRONE_TAG}-linux-arm64"
      username:
        from_secret: docker_username
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

  - name: docker-publish-webhook
    image: plugins/docker
    settings:
      dockerfile: package/Dockerfile.webhook
      password:
        from_secret: docker_password
      repo: "rancher/harvester-network-webhook"
      tag: "${DRONE_TAG}-linux-arm64"
      username:
        from_secret: docker_username
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

---
kind: pipeline
name: manifest

steps:
  - name: push-manifest-head
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: "rancher/harvester-network-controller:${DRONE_BRANCH}-head"
      template: "rancher/harvester-network-controller:${DRONE_BRANCH}-head-OS-ARCH"
      ignore_missing: true
      platforms:
        - linux/amd64
        - linux/arm64
    when:
      ref:
        include:
          - refs/heads/master
          - refs/heads/release/v*
      event:
        - push

  - name: push-manifest-tag
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: "rancher/harvester-network-controller:${DRONE_TAG}"
      template: "rancher/harvester-network-controller:${DRONE_TAG}-OS-ARCH"
      ignore_missing: true
      platforms:
        - linux/amd64
        - linux/arm64
    when:
      ref:
        include:
          - refs/head/master
          - refs/tags/*
      event:
        - tag

  - name: push-webhook-manifest-head
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: "rancher/harvester-network-webhook:${DRONE_BRANCH}-head"
      template: "rancher/harvester-network-webhook:${DRONE_BRANCH}-head-OS-ARCH"
      ignore_missing: true
      platforms:
        - linux/amd64
        - linux/arm64
    when:
      ref:
        include:
          - refs/heads/master
          - refs/heads/release/v*
      event:
        - push

  - name: push-webhook-manifest-tag
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: "rancher/harvester-network-webhook:${DRONE_TAG}"
      template: "rancher/harvester-network-webhook:${DRONE_TAG}-OS-ARCH"
      ignore_missing: true
      platforms:
        - linux/amd64
        - linux/arm64
    when:
      ref:
        include:
          - refs/head/master
          - refs/tags/*
      event:
        - tag

  - name: push-helper-manifest-head
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: "rancher/harvester-network-helper:${DRONE_BRANCH}-head"
      template: "rancher/harvester-network-helper:${DRONE_BRANCH}-head-OS-ARCH"
      ignore_missing: true
      platforms:
        - linux/amd64
        - linux/arm64
    when:
      ref:
        include:
          - refs/heads/master
          - refs/heads/release/v*
      event:
        - push

  - name: push-helper-manifest-tag
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: "rancher/harvester-network-helper:${DRONE_TAG}"
      template: "rancher/harvester-network-helper:${DRONE_TAG}-OS-ARCH"
      ignore_missing: true
      platforms:
        - linux/amd64
        - linux/arm64
    when:
      ref:
        include:
          - refs/head/master
          - refs/tags/*
      event:
        - tag

depends_on:
  - amd64
  - arm64
