apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: harvester-network-controller
    app.kubernetes.io/component: network
    app.kubernetes.io/version: 0.2.0
  name: harvester-network-controller
  namespace: harvester-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: harvester-network-controller
rules:
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    verbs: [ "*" ]
  - apiGroups: [ "network.harvesterhci.io" ]
    resources: [ "clusternetworks", "nodenetworks" ]
    verbs: [ "*" ]
  - apiGroups: [ "k8s.cni.cncf.io" ]
    resources: [ "network-attachment-definitions" ]
    verbs: [ "get", "watch", "list", "update" ]
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "get", "watch", "list", "update" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps", "events" ]
    verbs: [ "get", "watch", "list", "update", "create" ]
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "apps" ]
    resources: [ "daemonsets" ]
    verbs: [ "watch", "list", "update" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: harvester-network-controller
    app.kubernetes.io/component: network
    app.kubernetes.io/version: 0.2.0
  name: harvester-network-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: harvester-network-controller
subjects:
  - kind: ServiceAccount
    name: harvester-network-controller
    namespace: harvester-system